name: Node.js CI for 2.x

on:
  push:
    branches: [2.x]
  pull_request:
    branches: [2.x]
  merge_group:

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      os: 'ubuntu-latest, macos-latest, windows-latest'
      version: '18.19.0, 18, 20, 22, 24'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
